services:
  mongorep:
    image: ${DOCKER_REGISTRY-}mongorep
    build:
      context: .
      dockerfile: MongoRep/Dockerfile

# MONGO
  mongo-single:
    image: "mongo"
    container_name: mongo-single
    ports:
      - 27044:27017